spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.25:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  mvc:
    static-path-pattern: /static/**


server:
  port: 8081

mybatis:
  mapper-locations: classpath:mapperxml/*Mapper.xml
  type-aliases-package: com.hive.demo.model
